import Image from "next/image";

export function MeetingNotesSection() {
  return (
    <section className="mx-auto flex w-full max-w-7xl flex-col items-center gap-10 px-5 md:gap-14 md:px-8 py-20 lg:py-28">
      {/* Section header */}
      <div className="text-center">
        <h2
          className="font-sans font-semibold text-[#040406]"
          style={{ fontSize: "clamp(28px, 3vw, 44px)", lineHeight: 1.1 }}
        >
          Instant meeting notes
        </h2>
        <p
          className="mt-3 font-sans font-normal"
          style={{ fontSize: "18px", color: "rgb(120, 120, 135)" }}
        >
          The easiest way to get beautiful, shareable meeting notes.
        </p>
      </div>

      {/* Screenshot container */}
      <div
        className="w-full overflow-hidden rounded-[20px]"
        style={{
          background: "rgb(226, 230, 242)",
          padding: "24px 24px 0 24px",
        }}
      >
        <Image
          src="/images/desktop-notes.png"
          alt="Meeting notes generated by Cluely"
          width={3966}
          height={2536}
          className="w-full h-auto block rounded-t-xl"
          priority={false}
        />
      </div>
    </section>
  );
}
